# -*- coding: utf-8 -*-
"""Pandas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14uSHFvxeEOP7-5Wx2bx-dApIe02l451H
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd

df = pd.read_csv("hr_practice_dataset.csv")
df

df.head()
df.tail()

df.shape

df.info()

df.isnull().sum()

df["Department"].nunique()

df["Department"].unique()

df['Emp_Name'].count()

df[df["Salary"] > 70000]

df.groupby("Gender").count()

df["Department"].value_counts()

df.groupby("Department")["Salary"].mean()

df.groupby("Department")["Salary"].mean().sort_values(ascending = False).head(1)

df["Salary"].min() , df["Salary"].max()

df.sort_values(by="Salary", ascending=False)[
    ["Emp_ID", "Emp_Name", "Department", "Salary"]
].head(5)

df["EmploymentStatus"].value_counts()

#df.groupby("Year")["Emp_Name"].count()

df[df["PerformanceScore"] == "Exceeds"]

df[df["Salary"] > df.groupby("Department")["Salary"].transform("mean")]

