# -*- coding: utf-8 -*-
"""pratice pd.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DO9uyi0xmsSJ9rcOr4yJ5i6ybmsh2uPU
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df =pd.read_csv("titanic_practice_dataset.csv")
df

df.head(10)

df.shape

df.isnull().sum()

df[df["Survived"] == 1].shape

df["Age"].mean()

df.groupby("Sex").count()

df["Survived"].mean()*100

df.groupby("Pclass")["Fare"].count()

df.groupby("Sex")["Survived"].count()

df.groupby("Pclass")["Survived"].count()

df["Age"].sort_values(ascending=False).head(1) , df["Age"].sort_values(ascending=True).head(1)

df[df["Fare"] > 100 ]

df.groupby("Embarked")["PassengerId"].count()

df.groupby('Survived')['Age'].mean().rename({
    0: "Not Survived",
    1: "Survived"
})

df["Parents"] = df["SibSp"] + df["Parch"]
df

df.groupby("Parents")["Survived"].mean().sort_values(ascending=False).head(1)

df['FareGroup'] = pd.cut(df['Fare'],
                         bins=[0, 25, 50, 100, 250],
                         labels=['Low', 'Medium', 'High', 'Very High'])

df.groupby('FareGroup')['Survived'].mean() * 100

df.groupby("Pclass")["Survived"].mean()

df.groupby("Pclass")["Survived"].agg(
    SurvivalRate="mean",
    PassengerCount="count"
).sort_values(by="SurvivalRate", ascending=False)

df['AgeGroup'] = pd.cut(
    df['Age'],
    bins=[0, 12, 50, 100],
    labels=['Child', 'Adult', 'Senior']
)
df[['Age', 'AgeGroup']]
df.groupby('AgeGroup')['Survived'].mean()

df.corr(numeric_only=True)['Survived'].sort_values(ascending=False)

df["ALONE"] = (df["Parents"] == 0 ). astype(int)
df

df["HasCabin"] = df["Cabin"].notnull().astype(int)

df.drop("Cabin", axis=1, inplace=True)

df