# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fvBJ99k2Q_sJwuLifeSohbGag-azCuoy
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
df = pd.read_csv("HRDataset_v14.csv")
df

df.info()

df.isnull().sum()[df.isnull().sum()>0]

df["Department"].nunique()

df.groupby("GenderID").count()

df["Salary"].mean()

df["Salary"].min() , df["Salary"].max()

df[df["Department"] == "IT/IS"]

df[df["Salary"] > 80000]

df[df["EmploymentStatus"] == "Terminated for Cause"]

df[df["Absences"] > 10]

df.sort_values(by="Salary", ascending=False)[["Employee_Name","EmpID"]].tail(5)

df["Department"].value_counts()

df.groupby('Department')["Salary"].mean().sort_values(ascending = False).head(1)

df.groupby("DateofHire")["Employee_Name"].count()

df.groupby("ManagerName")["Employee_Name"].count()

df.groupby("RecruitmentSource").size().sort_values(ascending=False).head(1)

df.groupby("Department")["Absences"].mean()

df.groupby("GenderID")["Salary"].mean()

df[df["Salary"] > df.groupby("Department")["Salary"].transform(mean)]

df.groupby("ManagerName").size().sort_values(ascending=False).head(5)

df.groupby("Department")["EmpSatisfaction"].mean()[
    df.groupby("Department")["EmpSatisfaction"].mean() < df["EmpSatisfaction"].mean()
    ]

df["Salary"].drop_duplicates().sort_values(ascending=False).iloc[1]

df[
    (df["PerformanceScore"] == "Exceeds") &
    (df["EmploymentStatus"].isin(["Voluntarily Terminated", "Terminated for Cause"]))
]

df[
    (df["Salary"] > df.groupby("Department")["Salary"].transform("mean")) &
    (df["EngagementSurvey"] < df.groupby("Department")["EngagementSurvey"].transform("mean"))
]

pd.pivot_table(
    df,
    index="Department",
    columns="GenderID",
    values="Salary",
    aggfunc="mean"
)